export default {
  home: {
    roles: {
      role_00: 'Data & Artificial Intelligence Engineer',
      role_01: 'Data & AI Engineer',
      role_02: 'Full-Stack Developer',
      role_03: 'Software Developer',
      role_04: 'Unreal Developer'
    }
  },

  about: {
    shortDescription:
      'Full-Stack developer specialized in C++, Unreal Engine 5, and modern web architectures. Turning complex logic into seamless experiences.',
    description:
      'I am a Software and Data Engineer with a passion for transforming complex ideas into simple, high-impact solutions. My background combines logical thinking with a human perspective, allowing me to approach technical challenges with both critical analysis and empathy.\nCurrently, I focus on building high-performance systems and immersive experiences using Unreal Engine 5, C++, and Python. From real-time data processing to interactive game worlds, I strive to understand how things work at their core to deliver meticulous and efficient results.',
    degree: 'Bachelor'
  },

  skills: {
    description: ''
  },

  resume: {
    description: '',

    education: {
      demat: {
        degree: 'Computer Science',
        description_01:
          'Solving real problems using computational tools and relying on mathematical modeling methods.'
      },
      lidia: {
        degree: 'Data Engineer and Artificial Intelligence',
        description_01:
          'Information processing through the use of intelligent systems that enable strategic decision making for the different social and productive sectors.'
      }
    },

    experience: {
      enms_g: {
        position: 'Workshop Instructor',
        description_01:
          'Planning and implementation of an academic course on programming in Python language oriented to high school students.',
        description_02: 'Teaching the basics of programming using Python.',
        description_03: 'Developed the video game Bunnies and Badgers as a final project.'
      },
      mixtemi: {
        position: 'Front-End Developer',
        description_01: "Maintenance and updating of the organization's home page.",
        description_02:
          'Deployment and real time update of a menu for a Mexican fast food business.'
      },
      cfe: {
        position: 'Software Engineer',
        description_01:
          'Real-time retrieval, with Python, of new check-in and check-out records generated by the Multi-Biometric terminal for time and attendance management.',
        description_02:
          'Sending notification via institutional e-mail with MIME format to the employee when he/she generates a new record in the terminal.',
        description_03:
          'Development of a web application, with Flask, to manage the Multi-Biometric terminals, and review the records generated through a verification code in the mail sent in order to prevent fraud.'
      }
    },

    extracurricular: {
      unam_dts: {
        title: 'Data Science School: Benefits to Industry and Business from Data Analytics',
        description_01:
          'Training in the use of data analysis tools oriented to industry and science.'
      }
    }
  },

  contact: {
    description: ''
  }
};
